version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    groups:
      vitest:
        patterns:
          - 'vitest'
          - '@vitest/*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    groups:
      upload-download-artifact:
        patterns:
          - 'actions/upload-artifact'
          - 'actions/download-artifact'
    ignore:
      # Ignore versions after 1.4x
      # See https://github.com/changesets/action/issues/465
      - dependency-name: 'changesets/action'
        versions: ['>=1.5.0']
