name: Release

# Release with OIDC
# https://github.blog/changelog/2025-07-31-npm-trusted-publishing-with-oidc-is-generally-available/
# https://docs.npmjs.com/trusted-publishers

on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release new version
    runs-on: ubuntu-latest
    permissions:
      id-token: write # enable generation of an ID token for publishing
      pull-requests: write
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc

        # Ensure npm 11.5.1 or later is installed
      - run: npm install -g npm@latest
      - run: npm ci

      - name: Create Release PR or Publish to npm
        # See https://github.com/changesets/action/issues/465
        uses: changesets/action@v1.5.3
        with:
          publish: npm run release
          commit: 'chore: update version for release'
          title: 'chore: update version for release'
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
