# Release with OIDC
# https://github.blog/changelog/2025-07-31-npm-trusted-publishing-with-oidc-is-generally-available/
# https://docs.npmjs.com/trusted-publishers

name: Release

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Changesets release
    runs-on: ubuntu-latest
    permissions:
      actions: write # enable pushing changes to the origin
      contents: write # enable pushing changes to the origin
      id-token: write # enable generation of an ID token for publishing
      pull-requests: write # enable opening a PR for the release
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc

        # Ensure npm 11.5.1 or later is installed
      - run: npm install -g npm@latest
      - run: npm ci --ignore-scripts

      - name: Create Release PR or Publish to npm
        uses: changesets/action@v1
        with:
          publish: npm run release
          commit: 'chore: update version for release'
          title: 'chore: update version for release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
